/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelbookingpit;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ICE
 */
public class MainFrameBooking extends javax.swing.JFrame {
    
private TableRowSorter sorter;
DefaultTableModel table1;
String[]account1 = new String[100];
String[]account2 = new String[100];

int a1=0;


    /**
     * Creates new form MainFrameBooking
     */
    public MainFrameBooking() {
        initComponents();
               for(int m = 0; m<31;m++){
                dayin.addItem(m+1);
            }
               
               for(int n = 0; n<31;n++){
                dayout.addItem(n+1);
            }

        sorter = new TableRowSorter(table.getModel());
        table1 = (DefaultTableModel)table.getModel();
        table.setRowSorter(sorter);
        
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
        Register.setVisible(false);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignIn = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        loginbutton = new javax.swing.JButton();
        passfield = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pass1 = new javax.swing.JPasswordField();
        pass2 = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        filter1 = new javax.swing.JComboBox();
        filter2 = new javax.swing.JComboBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        returnbutton = new javax.swing.JButton();
        checkoutbutton = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        canvas1 = new java.awt.Canvas();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        availbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dayin = new javax.swing.JComboBox();
        yearout = new javax.swing.JComboBox();
        monthout = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        monthin = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        dayout = new javax.swing.JComboBox();
        phonefield = new javax.swing.JTextField();
        rtype = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        yearin = new javax.swing.JComboBox();
        bookbutton = new javax.swing.JButton();
        rnumber = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignIn.setBackground(new java.awt.Color(247, 243, 243));
        SignIn.setPreferredSize(new java.awt.Dimension(1252, 500));
        SignIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("comfortable and memorable one.");
        SignIn.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("and look forward to making your stay a ");
        SignIn.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("We are delighted to have you as our guest");
        SignIn.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 300, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Welcome to our Hotel Transylvania!");
        SignIn.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, 20));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingpit/dc3cc2e4108e6f55973d28641f64e465.jpg"))); // NOI18N
        jLabel28.setText("jLabel28");
        SignIn.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 370, 500));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(68, 105, 143));
        jLabel14.setText("SIGN IN");
        SignIn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 77));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Username:");
        SignIn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 77));

        userfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });
        SignIn.add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 202, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Password:");
        SignIn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 77));

        registerbutton.setBackground(java.awt.SystemColor.activeCaption);
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setText("Sign Up");
        registerbutton.setBorder(null);
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });
        SignIn.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, 60));

        loginbutton.setBackground(java.awt.SystemColor.activeCaption);
        loginbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.setBorder(null);
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        SignIn.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 190, 60));

        passfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SignIn.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 202, 40));

        jPanel6.setBackground(new java.awt.Color(218, 139, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        SignIn.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 80));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingpit/dc3cc2e4108e6f55973d28641f64e465.jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        SignIn.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 330, 550));

        jPanel4.setBackground(new java.awt.Color(68, 105, 143));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("GROUP 8");
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Sarmiento , Serg Louis B.");
        jPanel4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Rebote, Martian L.");
        jPanel4.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Catampatan, Mery Cris J.");
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Catindig Ronan Reil S.");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Salon, Mike Harlan S.");
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        SignIn.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 420, 500));

        getContentPane().add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1252, 500));

        Register.setBackground(new java.awt.Color(247, 243, 243));
        Register.setForeground(new java.awt.Color(204, 204, 204));
        Register.setMinimumSize(new java.awt.Dimension(1252, 500));
        Register.setPreferredSize(new java.awt.Dimension(1252, 500));
        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("all of them.");
        Register.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("registering, you'll have access to");
        Register.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Our hotel offers a wide range of ");
        Register.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("make your stay even more enjoyable. ");
        Register.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("We invite you to register with us and ");
        Register.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Confirm Password:");
        Register.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 130, 46));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Enter Password:");
        Register.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 110, 46));

        user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 260, 40));

        jButton1.setBackground(new java.awt.Color(218, 139, 20));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Register.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 205, 63));

        jButton2.setBackground(new java.awt.Color(218, 139, 20));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Return");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Register.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 205, 63));

        pass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });
        Register.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 260, 40));

        pass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass2ActionPerformed(evt);
            }
        });
        Register.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 260, 38));

        jPanel5.setBackground(new java.awt.Color(218, 139, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Register.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 510, 80));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingpit/dc3cc2e4108e6f55973d28641f64e465.jpg"))); // NOI18N
        jLabel45.setText("jLabel28");
        Register.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Enter Username:");
        Register.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 110, 46));

        jLabel26.setBackground(new java.awt.Color(68, 105, 143));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(68, 105, 143));
        jLabel26.setText("REGISTRATION");
        Register.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 77));

        jPanel3.setBackground(new java.awt.Color(68, 105, 143));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("About Us");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 33, -1, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("A hotel reservation is a process of booking a ");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("room at a hotel for a specific period of time. ");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("This can be done online, over the phone, or in person.");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("When making a reservation, guests ");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("typically provide their contact information,");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("arrival and departure dates, and the number of ");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("guests in their party. Some hotels also");
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("require a credit card deposit or advance payment");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("to secure the reservation.");
        jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("The hotel will then confirm the reservation and");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("provide guests with information about check-in");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("and check-out times, as well as any additional amenities");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("or services that are available.    ");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        Register.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 420, 500));

        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1252, 500));

        jPanel1.setBackground(new java.awt.Color(247, 243, 243));
        jPanel1.setPreferredSize(new java.awt.Dimension(1252, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Reserve your stay with us today ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("and experience the comfort and");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("luxury of our hotel. Our friendly staff is here");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("to assist you with your reservation and ");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("ensure that your visit with us is nothing");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("short of perfect.");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Phone No.", "Date In", "Date Out", "Room Type", "Room No."
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 853, 358));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingpit/dc3cc2e4108e6f55973d28641f64e465.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 500));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Filter:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 51, -1));

        filter1.setBackground(new java.awt.Color(204, 255, 255));
        filter1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Deluxe", "Suite" }));
        filter1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filter1ItemStateChanged(evt);
            }
        });
        filter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter1ActionPerformed(evt);
            }
        });
        jPanel1.add(filter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 134, -1));

        filter2.setBackground(new java.awt.Color(204, 255, 255));
        filter2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", " " }));
        filter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter2ActionPerformed(evt);
            }
        });
        jPanel1.add(filter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 134, -1));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButton1.setText("Sort");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 27, 89, -1));

        returnbutton.setBackground(new java.awt.Color(153, 204, 255));
        returnbutton.setText("Return");
        returnbutton.setBorder(null);
        returnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(returnbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 219, 40));

        checkoutbutton.setBackground(new java.awt.Color(153, 204, 255));
        checkoutbutton.setText("Check Out");
        checkoutbutton.setBorder(null);
        checkoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(checkoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 220, 40));

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButton2.setText("Unsort");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 27, 89, -1));
        jPanel1.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, 40));

        jLabel24.setText("experience the comfort and luxury of");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1252, 500));

        jPanel2.setBackground(new java.awt.Color(247, 243, 243));
        jPanel2.setPreferredSize(new java.awt.Dimension(1252, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Reserve your stay with us today ");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("and experience the comfort and");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("luxury of our hotel. Our friendly staff is here");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("to assist you with your reservation and ");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("ensure that your visit with us is nothing");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("short of perfect.");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        logout.setBackground(java.awt.SystemColor.activeCaption);
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setText("Logout");
        logout.setBorder(null);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 230, 40));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("DELUXE - PHP 1749");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 200, 40));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("SINGLE  - PHP 749");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, -1, -1));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("SUITE - PHP 2949");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, -1, -1));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setForeground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("DOUBLE - PHP 1049");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Phone:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 41, -1));

        availbutton.setBackground(new java.awt.Color(255, 204, 153));
        availbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        availbutton.setText("Check Occupied Rooms");
        availbutton.setBorder(null);
        availbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(availbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 220, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 41, -1));

        namefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        jPanel2.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 300, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Date Out:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        dayin.setBorder(null);
        dayin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayinActionPerformed(evt);
            }
        });
        jPanel2.add(dayin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 90, 30));

        yearout.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2023" }));
        yearout.setBorder(null);
        yearout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearoutActionPerformed(evt);
            }
        });
        jPanel2.add(yearout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 90, 30));

        monthout.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February" }));
        monthout.setBorder(null);
        monthout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthoutActionPerformed(evt);
            }
        });
        jPanel2.add(monthout, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Email:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 41, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Room Type:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        monthin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February" }));
        monthin.setBorder(null);
        monthin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthinActionPerformed(evt);
            }
        });
        jPanel2.add(monthin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Date In:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 50, -1));

        dayout.setBorder(null);
        dayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayoutActionPerformed(evt);
            }
        });
        jPanel2.add(dayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 90, 30));

        phonefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 300, 30));

        rtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Deluxe", "Suite" }));
        rtype.setBorder(null);
        rtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtypeActionPerformed(evt);
            }
        });
        jPanel2.add(rtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 105, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Room No:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 300, 30));

        yearin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2023" }));
        yearin.setBorder(null);
        yearin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearinActionPerformed(evt);
            }
        });
        jPanel2.add(yearin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 90, 30));

        bookbutton.setBackground(new java.awt.Color(255, 204, 153));
        bookbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookbutton.setText("Book");
        bookbutton.setBorder(null);
        bookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(bookbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 220, 40));

        rnumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        rnumber.setBorder(null);
        rnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnumberActionPerformed(evt);
            }
        });
        jPanel2.add(rnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 105, 30));

        jLabel9.setFont(new java.awt.Font("Trajan Pro 3", 1, 20)); // NOI18N
        jLabel9.setText("HOTEL RESERVATION FORM");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 330, 45));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingpit/dc3cc2e4108e6f55973d28641f64e465.jpg"))); // NOI18N
        jLabel29.setText("jLabel29");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 500));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingpit/Rectangle 20 (1).jpg"))); // NOI18N
        jLabel38.setText("jLabel38");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 260, 360));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1252, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbuttonActionPerformed

        String mi = monthin.getSelectedItem().toString();
        String mo = monthout.getSelectedItem().toString();
        String di = dayin.getSelectedItem().toString();
        String do1 = dayout.getSelectedItem().toString();

        
        if(namefield.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input name.");
        }
        
        else if(emailfield.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input email.");
        }
        
        else if(phonefield.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input phone number.");
        }
        
        else{
        
        
        if(mi.equals("February") && mo.equals("January")){
            JOptionPane.showMessageDialog(null, "Error Date.");
        }
            
        else {
            int di1 = Integer.parseInt(di);
            int do2 = Integer.parseInt(do1);
            
           
            if(di1>do2 && mi.equals(mo)){
                JOptionPane.showMessageDialog(null, "Error Date.");
            }
            else{
           String m1 = monthin.getSelectedItem().toString();
           String d1 = dayin.getSelectedItem().toString();
           String y1 = yearin.getSelectedItem().toString();
           
           String m2 = monthout.getSelectedItem().toString();
           String d2 = dayout.getSelectedItem().toString();
           String y2 = yearin.getSelectedItem().toString();
        
        
           String min = (String)monthin.getSelectedItem();
           String mout = (String)monthout.getSelectedItem();
       
           int x = 0;
           int y = Integer.parseInt(d2);
           int z = Integer.parseInt(d1);
           int amount = 0;
           
           String z1 = m1 +", " + d1 +" " + y1; 
           
           String z2 = m2 +", " + d2 +" " + y2;
           
           
           
           
            int j = 0;
            int i = 0;
            for (; i < table1.getRowCount(); i++) {
           
            String data1 = table1.getValueAt(i, 3).toString();
            String dd = table1.getValueAt(i, 5).toString();
            String cc = table1.getValueAt(i, 6).toString();
            String rtype1 = rtype.getSelectedItem().toString();
            String rnumber1 = rnumber.getSelectedItem().toString();
            
            if(z1.equals(data1) && rtype1.equals(dd) && rnumber1.equals(cc)){

                    j=1;
                    break;
                }
                else{
                    j=0;
                }
            }
            

 
    
    if(j==1){
        JOptionPane.showMessageDialog(null, "The Room you have selected is already occupied.");
    }
    else if (j==0){
     
           table1.addRow(new Object[]{
           namefield.getText(), emailfield.getText(), phonefield.getText(), z1, z2, rtype.getSelectedItem(), rnumber.getSelectedItem() 
        });
           namefield.setText(null);
           emailfield.setText(null);
           phonefield.setText(null);
           
           
           if (min != mout){
       switch(min){
           case "January":
               x = x + 31;      
              if(mout.equals("February")){
                   x = (y-z) + x + 1;
                   break;
               }
           
           case "February":
               x = x + 28;
               if(mout.equals("March")){
                   x = (y-z) + x + 1;
                   break;
               }
//            case "March":
//               x = x + 31;
//               if(mout.equals("April")){
//                   x = (y-z) + x + 1;
//                   break;
//               }
//               
//               case "April":
//               x = x + 30;
//               if(mout.equals("May")){
//                   x = (y-z) + x + 1;
//                   break;
//               }
//               
//               case "May":
//               x = x + 31;
//               if(mout.equals("June")){
//                  x = (y-z) + x + 1;
//                   break;
//               }
//               
//               case "June":
//               x = x + 30;
//               if(mout.equals("July")){
//                  x = (y-z) + x + 1;
//                   break;
//               }
//               
//               case "July":
//               x = x + 31;
//               if(mout.equals("August")){
//                  x = (y-z) + x + 1;
//                   break;
//               }
//               
//               case "August":
//               x = x + 31;
//               if(mout.equals("September")){
//                  x = (y-z) + x + 1;
//                   break;
//               }
//               
//               case "September":
//               x = x + 30;
//               if(mout.equals("October")){
//                  x = (y-z) + x + 1;
//                   break;
//               }
//               
//               case "October":
//               x = x + 31;
//               if(mout.equals("November")){
//                   x = (y-z) + x + 1;
//                   break;
//               }
//               
//               case "November":
//               x = x + 30;
//               if(mout.equals("December")){
//                   x = (y-z) + x + 1;
//                   break;
//               }
//               
//              case "December":
//               x = x + 30;
//               break;
//               
               
       }
       
               
               }
       else if(min == mout){
        x = y - z + 1;
       }
        
      if(rtype.getSelectedItem().equals("Single")){
          amount = x * 749;
           JOptionPane.showMessageDialog(null, "Successfully booked a Single Room which costs PHP 749 per night." + "\n Number of nights: " + x+ "\n The amount payable is: PHP " + amount);
       }
       else if(rtype.getSelectedItem().equals("Double")){
           amount = x * 1049;
           JOptionPane.showMessageDialog(null, "Successfully booked a Double Room which costs PHP 1049 per night." + "\n Number of nights: " + x+ "\n The amount payable is: PHP " + amount);
       }
       else if(rtype.getSelectedItem().equals("Deluxe")){
           amount = x * 1749;
           JOptionPane.showMessageDialog(null, "Successfully booked a Deluxe Room which costs PHP 1749 per night." + "\n Number of nights: " + x+ "\n The amount payable is: PHP " + amount);
       }
       else if (rtype.getSelectedItem().equals("Suite")){
           amount = x * 2949;
           JOptionPane.showMessageDialog(null, "Successfully booked a Suite Room which costs PHP 2949 per night." + "\n Number of nights: " + x+ "\n The amount payable is: PHP " + amount);
       }
      
            
    }  
           
       
       
        }    
           
        } 
       
        }
    }//GEN-LAST:event_bookbuttonActionPerformed

    private void availbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availbuttonActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
       
    }//GEN-LAST:event_availbuttonActionPerformed

    private void monthinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthinActionPerformed
 
         
        String selected1 = monthin.getSelectedItem().toString();
        dayin.removeAllItems();
        
        if(selected1.equals("January")){
         for(int n = 0; n<31;n++){
                dayin.addItem(n+1);
            }
        }
        
         if(selected1.equals("February")){
            
            for(int m = 0; m<28;m++){
                dayin.addItem(m+1);
            }
        }
       
        
        
    }//GEN-LAST:event_monthinActionPerformed

    private void monthoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthoutActionPerformed
              String selected1 = monthout.getSelectedItem().toString();
        dayout.removeAllItems();
        
        if(selected1.equals("January")){
                 for(int m = 0; m<31;m++){
                dayout.addItem(m+1);
            }
        }
        else if(selected1.equals("February")){
            
            for(int n = 0; n<28;n++){
                dayout.addItem(n+1);
            }
        }
    }//GEN-LAST:event_monthoutActionPerformed

    private void dayinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayinActionPerformed

    private void dayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayoutActionPerformed

    private void yearinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearinActionPerformed

    private void yearoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearoutActionPerformed

    private void rtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtypeActionPerformed

    private void rnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnumberActionPerformed

    private void returnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbuttonActionPerformed
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_returnbuttonActionPerformed

    private void checkoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbuttonActionPerformed
     try{
      
    int selectedrow1 = table.getSelectedRow();
       
    if(selectedrow1 != -1){
    table1.removeRow(table.convertRowIndexToModel(selectedrow1));
    table1.fireTableDataChanged();
    JOptionPane.showMessageDialog(null, "Successfully checked out!");
    }
    else{
       JOptionPane.showMessageDialog(null, "Please select one row in the table to check out.");
    }
     }
     catch(Exception e){
         System.out.println(e);
     }
     
       
    }//GEN-LAST:event_checkoutbuttonActionPerformed

    private void filter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter1ActionPerformed
       
    }//GEN-LAST:event_filter1ActionPerformed

    private void filter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter2ActionPerformed
      
    }//GEN-LAST:event_filter2ActionPerformed

    private void filter1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filter1ItemStateChanged

    }//GEN-LAST:event_filter1ItemStateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String f1 = filter1.getSelectedItem().toString();
        String f2 = filter2.getSelectedItem().toString();

      if(sorter == null){
      sorter = new TableRowSorter(table.getModel());
      table.setRowSorter(sorter);
    }
        List<RowFilter<Object,Object>> filters = new ArrayList<>(2);
        filters.add(RowFilter.regexFilter("^" + f1 + "$", 5));
        filters.add(RowFilter.regexFilter("^" + f2 + "$", 6));
        sorter.setRowFilter(RowFilter.andFilter(filters));

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        sorter = null;
        table.setRowSorter(null);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
      String userfield1 = userfield.getText();
      String psw = "";
      char[] passfield1 = passfield.getPassword();
      
        
      for(int x = 0; x<passfield1.length;x++){
            psw += passfield1[x];
        }
      
      for(int x =0; x<100;x++){
        if(userfield1.equals(account1[x])){
            if(psw.equals(account2[x])){
          SignIn.setVisible(false);
          jPanel2.setVisible(true);
//          NewJFrame k = new NewJFrame();
//        JOptionPane.getRootFrame().dispose();
//        k.setVisible(true);
          break;
            }
       
            else{
                JOptionPane.showMessageDialog(null, "Incorrect Password.");
                break;
            }
      }
        else if (x==99){
          JOptionPane.showMessageDialog(null, "Incorrect Username.");
          break;
      }
      }
    
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
       Register.setVisible(true);
       SignIn.setVisible(false);
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String ps1 = "";
        String ps2 = "";
        char[]passw1 = pass1.getPassword();
        char[]passw2 = pass2.getPassword();
        
        for(int x = 0; x<passw1.length;x++){
            ps1 += passw1[x];
        }
        
       for(int y = 0; y<passw2.length;y++){
            ps2 += passw2[y];
        }
       
       if (user.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Please fill up username.");
       }
       
       else if (ps1.equals("")){
           JOptionPane.showMessageDialog(null, "Please fill up password.");
       }    
       
       else{
       int z =0;
        for(; z<100;z++){
            if(user.getText().equals(account1[z])){
                JOptionPane.showMessageDialog(null, "Username already taken.");
                break;
            }
        }
        if(z==100 && ps1.equals(ps2)){
          String username = user.getText();
          String password = ps1;
          
          account1[a1] = username;
          account2[a1] = password;
          
          a1 = a1+1;
           
           JOptionPane.showMessageDialog(null, "Registered Successully.");
           user.setText(null);
           pass1.setText(null);
           pass2.setText(null);
           
       }
        else if(z==100 && !ps1.equals(ps2)) {
           JOptionPane.showMessageDialog(null, "Password does not match.");
       }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Register.setVisible(false);
       SignIn.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    private void pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass2ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
      SignIn.setVisible(true);
      jPanel2.setVisible(false);
      
      userfield.setText(null);
      passfield.setText(null);
    }//GEN-LAST:event_logoutActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Register;
    private javax.swing.JPanel SignIn;
    private javax.swing.JButton availbutton;
    private javax.swing.JButton bookbutton;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton checkoutbutton;
    private javax.swing.JComboBox dayin;
    private javax.swing.JComboBox dayout;
    private javax.swing.JTextField emailfield;
    private javax.swing.JComboBox filter1;
    private javax.swing.JComboBox filter2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox monthin;
    private javax.swing.JComboBox monthout;
    private javax.swing.JTextField namefield;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton registerbutton;
    private javax.swing.JButton returnbutton;
    private javax.swing.JComboBox rnumber;
    private javax.swing.JComboBox rtype;
    private javax.swing.JTable table;
    private javax.swing.JTextField user;
    private javax.swing.JTextField userfield;
    private javax.swing.JComboBox yearin;
    private javax.swing.JComboBox yearout;
    // End of variables declaration//GEN-END:variables
}
